remote_theme: pages-themes/modernist@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Data Portal Test on Github Pages
author: Preethi Siva
description: Just trying to figure out how to leverage this for our team
